#!/bin/bash
v=(1 2 3 4 5 6 7)
cant=0
for (( i = 0; i < 6; i++ )); do
  dividir=$((v[$i]} % 2))
  If [[ $dividir -eq 0 ]]; then
   echo "El numero par es: ${v[$i]}"
  else
   $cant=$((cant+1))
  fi
done
echo "La cantidad de impares es: $cant
